name: Main Branch Push
on:
  push:
    branches:
      - main

jobs:
  main-branch-push:
    runs-on: [self-hosted, 1ES.Pool=terraform-azure-modules]
    steps:
      - uses: 8BitJonny/gh-get-current-pr@2215326c76d51bfa3f2af0a470f32677f6c0cae9 # 2.2.0
        id: PR
      - name: checkout
        if: steps.PR.outputs.number != ''
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0
      - name: Download pr tfplan
        if: steps.PR.outputs.number != ''
        run: |
          az login --identity --username $MSI_ID > /dev/null
          az storage blob download --account-name tfmodrunnerstatestorage --auth-mode login --container-name azure-verified-tfmod-pull-request-plans --name tfplan_${{steps.PR.outputs.number}} --no-progress --file tfplan
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # 2.0.3
      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@1f9053d47a9645fe54d5de63ea2461083e0dc8f9 # 1.0.8
      - name: Apply
        if: steps.PR.outputs.number != ''
        run: |
          sh scripts/terragrunt-init.sh
          terragrunt apply -auto-approve -compact-warnings tfplan
      - name: Delete tfplan file
        if: steps.PR.outputs.number != ''
        run: |
          az storage blob delete --account-name tfmodrunnerstatestorage --auth-mode login --container-name azure-verified-tfmod-pull-request-plans --name tfplan_${{steps.PR.outputs.number}}